defaults: &defaults
  working_directory: ~/site-audit-tool
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    TERM: dumb
    PHPUNIT_ARGS: ""
    PHP_SENDMAIL_PATH: /dev/null

version: 2.1
jobs:
  test_72_drupal8:
    <<: *defaults
    docker:
      - image: wodby/php:7.2
        environment:
          - MYSQL_HOST=127.0.0.1
          - UNISH_DB_URL=mysql://root:@127.0.0.1
      - image: circleci/mysql:5.7.24
    steps:
      - checkout
      - run: cp .circleci/zz-php.ini /usr/local/etc/php/conf.d/
      - run: composer install -n
      - run: composer test

  test_72_drush8:
    <<: *defaults
    docker:
      - image: wodby/php:7.2
        environment:
          - MYSQL_HOST=127.0.0.1
          - UNISH_DB_URL=mysql://root:@127.0.0.1
      - image: circleci/mysql:5.7.24
    steps:
      - checkout
      - run: cp .circleci/zz-php.ini /usr/local/etc/php/conf.d/
      - run: .scenarios.lock/install drush8
      - run: composer test

  test_73_drupal9:
    <<: *defaults
    docker:
      - image: wodby/php:7.3
        environment:
          - MYSQL_HOST=127.0.0.1
          - UNISH_DB_URL=mysql://root:@127.0.0.1
      - image: circleci/mysql:5.7.24
    steps:
      - checkout
      - run: cp .circleci/zz-php.ini /usr/local/etc/php/conf.d/
      - run: .scenarios.lock/install drupal9
      - run: composer test

  test_56_drupal87:
    <<: *defaults
    docker:
      - image: wodby/php:5.6
        environment:
          - MYSQL_HOST=127.0.0.1
          - UNISH_DB_URL=mysql://root:@127.0.0.1
      - image: circleci/mysql:5.7.24
    steps:
      - checkout
      - run: cp .circleci/zz-php.ini /usr/local/etc/php/conf.d/

      # We need Composer 1.x in order to run tests on PHP 5.6,
      # and this needs to be installed manually.
      - run: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - run: php -r "if (hash_file('sha384', 'composer-setup.php') === 'c31c1e292ad7be5f49291169c0ac8f683499edddcfd4e42232982d0fd193004208a58ff6f353fde0012d35fdd72bc394') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
      - run: php composer-setup.php --version=1.10.16
      - run: php -r "unlink('composer-setup.php');"

      - run: .scenarios.lock/install php56
      - run: php composer.phar drupal:scaffold
      - run: php composer.phar test

workflows:
  version: 2
  example-drush-extension:
    jobs:
      - test_72_drupal8
      - test_72_drush8
      - test_73_drupal9
      - test_56_drupal87

